defaultPlacement: end
enableVersioning: true
handle: blog
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - Preview
      -
        - urlFormat
        - '{{alias(''@nextjspreview'')}}id={canonicalId}&uid={uid}&type=blog'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b491c1f3-1e2c-444e-bb8c-87362f0186f2: # Craft Lndo
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry
    uriFormat: 'blog/{slug}'
type: channel
