columnSuffix: null
contentColumnType: string
fieldGroup: 24efe072-4e97-4a1c-9b76-92de17d6703f # Blog Post Fields
handle: featureImage
instructions: 'Add an image'
name: 'Feature Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:0e4c59cc-9360-46e6-8803-766dcc8cc6e7' # Blog
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:0e4c59cc-9360-46e6-8803-766dcc8cc6e7' # Blog
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:0e4c59cc-9360-46e6-8803-766dcc8cc6e7' # Blog
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
