columnSuffix: null
contentColumnType: string
fieldGroup: 24efe072-4e97-4a1c-9b76-92de17d6703f # Blog Post Fields
handle: postContent
instructions: 'Post Content'
name: 'Post Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_postcontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
