columnSuffix: rthggceu
contentColumnType: text
fieldGroup: 24efe072-4e97-4a1c-9b76-92de17d6703f # Blog Post Fields
handle: summary
instructions: 'Enter a brief summary.'
name: Summary
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
