dateModified: 1668545822
email:
  fromEmail: ellisjoshuag@gmail.com
  fromName: 'Craft Lndo'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0e0fc622-b40f-4510-8efc-d3545b224d3c: Summary # Summary
    0e4c59cc-9360-46e6-8803-766dcc8cc6e7: Blog # Blog
    3e94519e-c183-4758-a42d-b9091c4c269f: Text # Text
    5e2c324c-1739-449f-abf9-ca25cc0eef0c: 'Site Information' # Site Information
    7ab9b734-3e5e-4c36-902e-af34d815fa03: 'Post Content' # Post Content
    7c3e3e27-f5af-407c-9328-cf5c9069ca63: 'Global Fields' # Global Fields
    8d4bfe46-1319-4948-9a99-42f95c16c73f: 'Craft Lndo' # Craft Lndo
    9db36701-5513-4dd5-82aa-7f4dd7451494: 'Blog Categories' # Blog Categories
    24efe072-4e97-4a1c-9b76-92de17d6703f: 'Blog Post Fields' # Blog Post Fields
    393d116b-e1e4-47f7-b336-34b0d74d89b1: Text # Text
    040309a0-e938-49a8-b5f1-aa73e7f07954: Image # Image
    5233556e-0455-41e8-98f3-2fc9af4975a9: 'New Field' # New Field
    b021ad4a-13e8-45a5-a935-8786e307a963: Common # Common
    b491c1f3-1e2c-444e-bb8c-87362f0186f2: 'Craft Lndo' # Craft Lndo
    c01be25d-dd61-410e-a24b-e37430f2b3cc: 'Site Description' # Site Description
    c073b09e-4c2e-469f-8b63-f21783ce7a92: Blog # Blog
    c5c0cd42-a578-4900-98d2-1ed88ee2103b: 'Post Categories' # Post Categories
    d6a35ddb-0943-4d13-9775-c3848c358abd: Image # Image
    d7eccf20-c088-4a92-b520-d1ef7c402a6c: 'Feature Image' # Feature Image
    d6709d54-6517-49bd-aad4-b7a3ffea6ce4: Blog # Blog
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: solo
  live: true
  name: 'Craft Lndo'
  schemaVersion: 3.7.33
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
